name: solar-system-workflow
on:
    workflow_dispatch:
    push:
        branches:
            - main
            - feature/*
env:
    MONGO_URI: mongodb://127.0.0.1:27017/solar-system
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ vars.MONGO_PASSWORD }}
jobs:
    unit-testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup NodeJS Version - 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Run unit tests
              run: npm test